- name: Update the cache and all packages to their latest version
  become: True
  apt:
    update_cache: yes
    name: "*"
    state: latest

- name: Install some packages
  become: True
  apt:
    update_cache: yes
    pkg:
      - curl
      - htop
      - wget
      - nano
      - python3
      - python3-pip

- name: Remove dependencies that are no longer required
  become: True
  apt:
    autoremove: yes